#!/usr/bin/env bash

# Helper script to run test for each supported python versions
# Defaults to running basic tests. The script activates the correct environment
# as required.

# Usage: $0 [options]
# Example: $0 --ro-functional

ARGS="$@"

for BIN in python2 python3; do
    if command -v ${BIN} >/dev/null 2>&1; then
        echo "INFO: Activating environment for ${BIN}"
        . ./contrib/activate-dev-env ${BIN}
        if [ -z ${VIRTUAL_ENV} ]; then
            echo "WARN: Virtual Environment not active, skipping tests."
        else
            echo "INFO: Running tests for ${BIN}"
            python setup.py test ${ARGS}
            echo "INFO: Tests completed for ${BIN}"
        fi
    else
        echo "INFO: ${BIN} not found, skipping tests."
    fi
done
