.TH bugzilla 1  "December 12, 2007" "version 0.1" "USER COMMANDS"
.SH NAME
bugzilla - command-line interface to Bugzilla over XML-RPC
.SH SYNOPSIS
.B bugzilla
[command] [options]
.SH DESCRIPTION
.B bugzilla
is a command-line utility that allows access to the XML-RPC interface provided
by Bugzilla.
.SH OPTIONS
.TP
\-\-help
Get help.
.SH EXAMPLES
.TP
TODO.
.SH EXIT STATUS
Also TODO.
.SH AUTHOR
Will Woods <wwoods@redhat.com>
